"""initial schema

Revision ID: 44b11a924b17
Revises: 
Create Date: 2026-03-20 03:54:15.743696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b11a924b17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arguments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(body) BETWEEN 50 AND 2000', name='body_length'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arguments_composite_score', 'arguments', ['composite_score'], unique=False)
    op.create_index('idx_arguments_status', 'arguments', ['status'], unique=False)
    op.create_index('idx_arguments_topic_id', 'arguments', ['topic_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('argument_id', sa.UUID(), nullable=False),
    sa.Column('rubric', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rubric IN ('logic', 'evidence', 'persuasion', 'originality')", name='valid_rubric'),
    sa.CheckConstraint('score BETWEEN 1 AND 10', name='valid_score'),
    sa.ForeignKeyConstraint(['argument_id'], ['arguments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('argument_id', 'rubric', name='uq_argument_rubric')
    )
    op.create_index('idx_scores_argument_id', 'scores', ['argument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scores_argument_id', table_name='scores')
    op.drop_table('scores')
    op.drop_index('idx_arguments_topic_id', table_name='arguments')
    op.drop_index('idx_arguments_status', table_name='arguments')
    op.drop_index('idx_arguments_composite_score', table_name='arguments')
    op.drop_table('arguments')
    op.drop_table('topics')
    # ### end Alembic commands ###
